name: ZenMaxBuilder CI

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9"
          source_branch: "lineage-19.1"
          destination_branch: "ZenMaxBuilder"
          github_token: ${{ secrets.PAT }}
